# Generated by Django 5.0 on 2023-12-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(default='e', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='observation',
            field=models.CharField(default='e', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(default='e', max_length=50),
            preserve_default=False,
        ),
    ]
